### ISSUE TITLE
Cleaned Up Isles Map

### ISSUE THREAD

**Issue by cmcoffin** [Electric-Fortune/bananatracker#1]
I made a cleaned up version of the Isles map that removes the text at the top and gets rid of that page crease in the scan if you're interested you can use it here.
![map_isles](https://github.com/Electric-Fortune/bananatracker/assets/5597556/316827bc-b8f0-4d9b-b015-fe4999a80b62)

**Comment by Electric-Fortune** [comment]
This looks good! I'll definitely pull this into the next release, it always bugged me that Isles had a lower quality than the rest :P

**Comment by Electric-Fortune** [comment]
This has now been implemented in v1.4.0. Thanks again for the cleaned up file!
